"""admin entities

Revision ID: 73027eb4b1d1
Revises: 
Create Date: 2026-02-13 16:24:08.284670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73027eb4b1d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_accounts_email'), 'admin_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_admin_accounts_id'), 'admin_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_admin_accounts_username'), 'admin_accounts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_accounts_username'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_id'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_email'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
