"""vendor comments

Revision ID: 89c3d495e17e
Revises: be04446ff65c
Create Date: 2026-02-05 16:18:04.036210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c3d495e17e'
down_revision: Union[str, Sequence[str], None] = 'be04446ff65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_interests', 'country_code')
    op.add_column('vendors', sa.Column('category', sa.String(), nullable=False))
    op.drop_constraint('vendors_category_id_fkey', 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'category_id')
    op.drop_column('vendors', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendors_category_id_fkey', 'vendors', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vendors', 'category')
    op.add_column('customer_interests', sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
