"""vendor comments

Revision ID: cbb7d407c490
Revises: 6bb9ba4933d9
Create Date: 2026-02-05 16:45:48.813950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb7d407c490'
down_revision: Union[str, Sequence[str], None] = '6bb9ba4933d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
