"""onboard fee

Revision ID: d0cdf3db049b
Revises: 
Create Date: 2026-03-16 13:15:02.030685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cdf3db049b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_order_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('payment_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_payments_provider_payment_id', table_name='payments')
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.drop_column('payments', 'provider_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.create_index('ix_payments_provider_payment_id', 'payments', ['provider_payment_id'], unique=False)
    op.drop_column('payments', 'payment_id')
    op.drop_column('payments', 'provider_order_id')
    # ### end Alembic commands ###
