"""fix

Revision ID: 44d4160c448d
Revises: 
Create Date: 2026-02-06 16:53:45.690126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d4160c448d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_interests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_interests_email'), 'vendor_interests', ['email'], unique=True)
    op.create_index(op.f('ix_vendor_interests_id'), 'vendor_interests', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_interests_phone_number'), 'vendor_interests', ['phone_number'], unique=False)
    op.add_column('vendors', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('vendors', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendors', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('vendors', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_vendors_phone_number', table_name='vendors')
    op.create_index(op.f('ix_vendors_phone_number'), 'vendors', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_phone_number'), table_name='vendors')
    op.create_index('ix_vendors_phone_number', 'vendors', ['phone_number'], unique=False)
    op.alter_column('vendors', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('vendors', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('vendors', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendors', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('vendors', 'is_active')
    op.drop_index(op.f('ix_vendor_interests_phone_number'), table_name='vendor_interests')
    op.drop_index(op.f('ix_vendor_interests_id'), table_name='vendor_interests')
    op.drop_index(op.f('ix_vendor_interests_email'), table_name='vendor_interests')
    op.drop_table('vendor_interests')
    # ### end Alembic commands ###
