"""vendor comments

Revision ID: 6bb9ba4933d9
Revises: 89c3d495e17e
Create Date: 2026-02-05 16:35:39.460336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb9ba4933d9'
down_revision: Union[str, Sequence[str], None] = '89c3d495e17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_interests', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_interests', 'name')
    # ### end Alembic commands ###
