"""metadata

Revision ID: d3159446b485
Revises: 
Create Date: 2026-04-14 14:57:17.232181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3159446b485'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_payment_metadata',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'customer_id', 'vendor_id', name='uq_token_payment_metadata_scope')
    )
    op.create_index(op.f('ix_token_payment_metadata_ad_id'), 'token_payment_metadata', ['ad_id'], unique=False)
    op.create_index(op.f('ix_token_payment_metadata_customer_id'), 'token_payment_metadata', ['customer_id'], unique=False)
    op.create_index(op.f('ix_token_payment_metadata_id'), 'token_payment_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_token_payment_metadata_vendor_id'), 'token_payment_metadata', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_payment_metadata_vendor_id'), table_name='token_payment_metadata')
    op.drop_index(op.f('ix_token_payment_metadata_id'), table_name='token_payment_metadata')
    op.drop_index(op.f('ix_token_payment_metadata_customer_id'), table_name='token_payment_metadata')
    op.drop_index(op.f('ix_token_payment_metadata_ad_id'), table_name='token_payment_metadata')
    op.drop_table('token_payment_metadata')
    # ### end Alembic commands ###
